package com.waalert.whatsapp_alert_backend.service;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import jakarta.mail.*;
import jakarta.mail.internet.*;
import java.util.Properties;

/**
 * EmailService — Spring Boot equivalent of the Python script's send_email():
 *
 *   def send_email(subject, body, to_email):
 *       msg = MIMEMultipart()
 *       server = smtplib.SMTP("smtp.gmail.com", 587)
 *       server.starttls()
 *       server.login("your_email", "password")
 *       server.send_message(msg)
 *
 * Requires jakarta.mail dependency (included via spring-boot-starter-mail
 * OR add explicitly — see note below).
 *
 * NOTE: Add this to pom.xml if you want email output:
 *   <dependency>
 *       <groupId>org.springframework.boot</groupId>
 *       <artifactId>spring-boot-starter-mail</artifactId>
 *   </dependency>
 */
@Service
@Slf4j
public class EmailService {

    @Value("${mail.smtp.host:smtp.gmail.com}")
    private String smtpHost;

    @Value("${mail.smtp.port:587}")
    private int smtpPort;

    @Value("${mail.from:noreply@yourapp.com}")
    private String fromAddress;

    @Value("${mail.username:your_email@gmail.com}")
    private String username;

    @Value("${mail.password:your_password}")
    private String password;

    /**
     * Sends an HTML email — equivalent to the Python send_email() function.
     *
     * @param subject  email subject line
     * @param htmlBody HTML body (tables, formatted data)
     * @param toEmail  recipient email address
     */
    public void sendEmail(String subject, String htmlBody, String toEmail) {
        Properties props = new Properties();
        props.put("mail.smtp.auth",            "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host",            smtpHost);
        props.put("mail.smtp.port",            String.valueOf(smtpPort));
        props.put("mail.smtp.ssl.trust",       smtpHost);

        Session session = Session.getInstance(props, new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });

        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(fromAddress));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(toEmail));
            message.setSubject(subject);

            // HTML body
            MimeBodyPart htmlPart = new MimeBodyPart();
            htmlPart.setContent(htmlBody, "text/html; charset=utf-8");

            Multipart multipart = new MimeMultipart();
            multipart.addBodyPart(htmlPart);
            message.setContent(multipart);

            Transport.send(message);
            log.info("Email sent to {} — subject: {}", toEmail, subject);

        } catch (MessagingException e) {
            log.error("Failed to send email to {}: {}", toEmail, e.getMessage());
            throw new RuntimeException("Email send failed: " + e.getMessage());
        }
    }

    /**
     * Builds an HTML table from query result data.
     * Equivalent to the Python:
     *   body = "<h3>Results</h3><table border=1>"
     *   for r in rows:
     *       body += f"<tr><td>{r[0]}</td><td>{r[1]}</td></tr>"
     */
    public String buildHtmlTable(String title, java.util.List<String> columns,
                                  java.util.List<java.util.List<Object>> rows) {
        StringBuilder html = new StringBuilder();
        html.append("<h3>").append(title).append("</h3>");
        html.append("<table border='1' cellpadding='5' cellspacing='0' style='border-collapse:collapse;font-family:Arial,sans-serif;'>");

        // Header row
        html.append("<tr style='background:#003366;color:white;'>");
        for (String col : columns) {
            html.append("<th>").append(col).append("</th>");
        }
        html.append("</tr>");

        // Data rows
        int rowNum = 0;
        for (java.util.List<Object> row : rows) {
            String bg = (rowNum++ % 2 == 0) ? "#ffffff" : "#f0f4ff";
            html.append("<tr style='background:").append(bg).append(";'>");
            for (Object val : row) {
                html.append("<td>").append(val != null ? val : "").append("</td>");
            }
            html.append("</tr>");
        }

        html.append("</table>");
        html.append("<p style='color:#666;font-size:12px;'>Generated by WA Alert System</p>");
        return html.toString();
    }
}
